services:
  - type: web
    name: duramet
    runtime: php
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
    autoDeploy: true
    healthCheckPath: /
